<a href="https://colab.research.google.com/github/Anik9034/Reinforcement-learning/blob/main/Qlearning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
R =np.matrix([[-1,-1,-1,-1,0,-1],
              [-1,-1,1,0,-1,100],
              [-1,-1,-1,0,-1,-1],
              [-1,0,0,-1,0,-1],
             [-1,0,0,-1,-1,100],
              [-1,0,-1,-1,0,100]])


In [2]:
R

matrix([[ -1,  -1,  -1,  -1,   0,  -1],
        [ -1,  -1,   1,   0,  -1, 100],
        [ -1,  -1,  -1,   0,  -1,  -1],
        [ -1,   0,   0,  -1,   0,  -1],
        [ -1,   0,   0,  -1,  -1, 100],
        [ -1,   0,  -1,  -1,   0, 100]])

In [4]:
Q = np.matrix(np.zeros([6,6]))
    


In [5]:
Q

matrix([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

In [6]:
gamma = 0.8
initial_state=1

In [7]:
def available_actions(state):
  current_state_row = R[state,]
  av_act = np.where(current_state_row>=0)[1]
  return av_act


In [8]:
available_act=available_actions(initial_state)

In [9]:
available_act

array([2, 3, 5])

In [10]:
def sample_next_action(available_actions_range):
  next_action=int(np.random.choice(available_act,1))
  return next_action

In [11]:
action=sample_next_action(available_act)

In [12]:
action

3

In [13]:
def update(current_state,action,gamma):
  max_index=np.where(Q[action,]==np.max(Q[action,]))[1]
  if max_index.shape[0]>1:
    max_index=int(np.random.choice(max_index,size=1))
  else:
      max_index=int(max_index)
      max_value=Q[action,max_index]
      Q[current_state,action]=R[current_state,action]+gamma*max_value
      
  update(initial_state,action,gamma)      
                  

In [14]:
Q

matrix([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

In [16]:
#Training
# Training over 10,000 iterations
for i in range(10000):
    current_state=np.random.randint(0,int(Q.shape[0]))
    availabe_act=available_actions(current_state)
    action=sample_next_action(available_act)
    update(current_state,action,gamma)
    
#normalize the trained Q-Matrix
print("Trained Q matrix:")
print(Q/np.max(Q)*100)
# print(Q)

RecursionError: ignored

In [15]:
#Training
#Train over 10,000 iterations
for i in range(10000):
  current_state=np.random.randit(0,int(Q.shape[0]))
  available=sample_next_actio(current_act)
  action=sample_next_action(availabel_act)
  update(current state,action,gamma)

  print()
  print()

SyntaxError: ignored

In [ ]:
current_state=1
steps=[current_state]

while current_state != 5:
  next_step_index=np.where(Q[current_state,]==np.max(Q[current_stae,]))[1]
  if next_step_index.shape[0]>1:
    next_step_index=int(np.random.choice(next_step_index,size=1))
    else:
      next_step_index=int(next_step_index)

    steps.append(next_step_index) 
    current_state=next_step_index

#print      